# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Catppuccin-Latte
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.5
# END_KITTY_FONTS
tab_bar_style custom

# BEGIN_KITTY_KEYMAP
macos_option_as_alt both


# cursor config

# Enable trail and match distance_stop_animating / long trail behavior
# cursor_trail 11

# Format: cursor_trail_decay <min_seconds> <max_seconds>
# cursor_trail_decay 0.05 0.55
# cursor_shape block
# shell_integration no-cursor


