#! /bin/zsh

yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20



# Force specific apps to always float
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Safari$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Slack$" manage=off



# yabai -m rule --add app="^DBeaver$" subrole="^AXDialog$"
# yabai -m query --windows | jq '.[] | select(.app=="DBeaver") | {title: .title, subrole: .subrole}'

# Force DBeaver and IntelliJ to tile by default
yabai -m rule --add app="^DBeaver$" manage=on
yabai -m rule --add app="^IntelliJ IDEA$" manage=on

# Float windows with common submenu words in the title
yabai -m rule --add app="^DBeaver$" title="Settings|Connection|Edit|Properties" manage=off
yabai -m rule --add app="^DBeaver$" title="^$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="Preferences|Settings|Structure|Commit" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^$" manage=off


yabai -m rule --apply

yabai -m config layout bsp
borders active_color=0xffc6a0f6 inactive_color=0xff494d64 width=5.0 &

