#! /bin/zsh

yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20
yabai -m config layout bsp



# Force specific apps to always float
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off



# yabai -m rule --add app="^DBeaver$" subrole="^AXDialog$"
# yabai -m query --windows | jq '.[] | select(.app=="DBeaver") | {title: .title, subrole: .subrole}'


borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

