#! /bin/zsh

yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20
yabai -m config layout bsp
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

